# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Nextjs Mongodb
env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}

on: workflow_dispatch

jobs:
  fetch-node-modules-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: List
        run: ls -la
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Show Env
        run: cat .vercel/.env.preview.local
      - name: Test and Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
